"""Nox session definitions for linting, testing, security scanning, and benchmarks."""

import os

import nox

# Use uv as the venv backend so nox sessions get their own isolated venvs
# managed by uv, without touching the project's .venv.
nox.options.default_venv_backend = 'uv'


def _lint_code(session: nox.Session) -> None:
    """Lint the project with ruff."""
    session.run(
        'ruff',
        'check',
        'noxfile.py',
        'glitchygames',
        'scripts',
        'tests',
    )


@nox.session(python=['3.13'], reuse_venv=False, name='format')
def _format(session: nox.Session) -> None:
    """Format the project."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    session.run(
        'ruff',
        'check',
        '--select',
        'I',
        '--fix',
        'noxfile.py',
    )
    session.run(
        'ruff',
        'check',
        '--select',
        'I',
        '--fix',
        'glitchygames',
    )
    session.run(
        'ruff',
        'check',
        '--select',
        'I',
        '--fix',
        'scripts',
    )
    session.run(
        'ruff',
        'check',
        '--select',
        'I',
        '--fix',
        'tests',
    )

    # Format code (ruff format is mostly black style)
    session.run(
        'ruff',
        'format',
        'noxfile.py',
    )
    session.run(
        'ruff',
        'format',
        'glitchygames',
    )
    session.run(
        'ruff',
        'format',
        'scripts',
    )
    session.run(
        'ruff',
        'format',
        'tests',
    )


@nox.session(python=['3.13'], reuse_venv=False)
def lint(session: nox.Session) -> None:
    """Lint the project with ruff."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    _lint_code(session)


@nox.session(python=['3.13'], reuse_venv=False)
def static_analysis(session: nox.Session) -> None:
    """Run static type analysis with basedpyright."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    session.run('basedpyright')


@nox.session(python=['3.13'], reuse_venv=False)
def ty_check(session: nox.Session) -> None:
    """Run static type analysis with ty (Astral's type checker)."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    session.run('ty', 'check')


@nox.session(python=['3.13'], reuse_venv=False)
def lint_docs(session: nox.Session) -> None:
    """Lint documentation with mkdocs strict build."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    session.run(
        'mkdocs',
        'build',
        '--strict',
    )


@nox.session(python=['3.13'], reuse_venv=False)
def test(session: nox.Session) -> None:
    """Run tests."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    # Use dummy SDL video driver in CI/headless environments to prevent segfaults.
    # This is set here so it applies before pygame is imported by any test worker.
    env = {}
    if os.environ.get('CI') == 'true' or os.environ.get('SDL_VIDEODRIVER') == 'dummy':
        env['SDL_VIDEODRIVER'] = 'dummy'

    # Run tests with coverage — all coverage reports (term, html, xml, json, lcov)
    # are generated by pytest-cov via pyproject.toml addopts.
    # JUnit XML output is stored for CI test result ingestion.
    session.run(
        'pytest',
        env=env,
    )


@nox.session(python=['3.13'], reuse_venv=False)
def security_scan(session: nox.Session) -> None:
    """Run security scanning tools."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    # Run bandit security scan
    # Exclude test dirs (B101 assert false positives)
    session.run(
        'bandit',
        '-r',
        'glitchygames',
        '--exclude',
        'glitchygames/tests',
        '-f',
        'json',
        '-o',
        'bandit-report.json',
    )

    # Run safety check for known vulnerabilities
    # Exclude .venv and .nox to avoid scanning third-party packages
    if not os.getenv('SAFETY_API_KEY'):
        session.log('SAFETY_API_KEY not set; skipping Safety scan.')
        return

    session.run(
        'safety',
        'scan',
        '--exclude',
        '.venv',
        '--exclude',
        '.nox',
        '--output',
        'screen',
        '--save-as',
        'json',
        'safety-report.json',
    )


@nox.session(python=['3.13'], reuse_venv=False)
def performance_test(session: nox.Session) -> None:
    """Run performance benchmarks."""
    # Install with all extras into the nox session venv.
    # Update this if new [project.optional-dependencies] sections are added.
    session.install('.[api,dev,docs]')

    # Run performance tests with pytest-benchmark
    # Override addopts to avoid conflict with --cov flags from pyproject.toml
    session.run(
        'pytest',
        '-o',
        'addopts=',
        '-p',
        'no:xdist',
        '--benchmark-only',
        '--benchmark-save=baseline',
        'tests/',
    )
