"""Type stubs for the apng library (https://pypi.org/project/apng/)."""

from typing import IO, BinaryIO

class FrameControl:
    width: int | None
    height: int | None
    x_offset: int
    y_offset: int
    delay: int
    delay_den: int
    depose_op: int
    blend_op: int

    def __init__(
        self,
        width: int | None = None,
        height: int | None = None,
        x_offset: int = 0,
        y_offset: int = 0,
        delay: int = 100,
        delay_den: int = 1000,
        depose_op: int = 1,
        blend_op: int = 0,
    ) -> None: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, b: bytes) -> FrameControl: ...

class PNG:
    def __init__(self) -> None: ...
    def init(self) -> None: ...
    def save(self, file: str | IO[bytes]) -> None: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, b: bytes) -> PNG: ...
    @classmethod
    def from_chunks(cls, chunks: list[tuple[str, bytes]]) -> PNG: ...

class APNG:
    frames: list[tuple[PNG, FrameControl]]
    num_plays: int

    def __init__(self, num_plays: int = 0) -> None: ...
    def append(self, png: PNG, **options: int) -> None: ...
    def append_file(self, file: str | IO[bytes], **options: int) -> None: ...
    def save(self, file: str | IO[bytes] | BinaryIO) -> None: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, b: bytes) -> APNG: ...
    @classmethod
    def open(cls, file: str | IO[bytes]) -> APNG: ...
