[sprite]
name = "animated_sprite"
pixels = """
................................
................................
................................
................................
..........aaaaaaaaaa............
..........aAAAAAAAAa............
..........aAAAAAAAAa............
..........aAAAAAAAAa............
..........aAAAAAAAAa............
..........aAAAAAAAAa............
..........aaaaaaaaaa............
..........abbbbbbbba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abBBBBBBba............
..........abbbbbbbba............
..........aaaaaaaaaa............
................................
................................
................................
................................
................................
................................
................................
................................
"""

[colors]
"." = { red = 255, green = 0, blue = 255 }
"a" = { red = 0, green = 0, blue = 0 }
"A" = { red = 255, green = 192, blue = 203 }
"b" = { red = 150, green = 75, blue = 0 }
"B" = { red = 218, green = 165, blue = 32 }
