#!/usr/bin/env python3
"""Glitchy Games event module.

This module contains the event substrate for handling
higher level events in the game engine.

Many events are 1:1 with pygame events, but some are
synthesized.  For example, a mouse drop event is
a synthesized event that is triggered by a mouse
button down event followed by a mouse motion event
followed by a mouse button up event.
"""

from glitchygames.events.base import (
    ALL_EVENTS,
    APP_EVENTS,
    AUDIO_EVENTS,
    CONTROLLER_EVENTS,
    DROP_EVENTS,
    FPSEVENT,
    GAME_EVENTS,
    GAMEEVENT,
    JOYSTICK_EVENTS,
    KEYBOARD_EVENTS,
    LOG,
    MENUEVENT,
    MIDI_EVENTS,
    MOUSE_EVENTS,
    TEXT_EVENTS,
    TOUCH_EVENTS,
    WINDOW_EVENTS,
    EventInterface,
    HashableEvent,
    ResourceManager,
    UnhandledEventError,
    supported_events,
    unhandled_event,
)
from glitchygames.events.input_event_interfaces import (
    ControllerEvents,
    ControllerEventStubs,
    JoystickEvents,
    JoystickEventStubs,
    KeyboardEvents,
    KeyboardEventStubs,
    MidiEvents,
    MidiEventStubs,
    MouseEvents,
    MouseEventStubs,
    TextEvents,
    TextEventStubs,
    TouchEvents,
    TouchEventStubs,
)
from glitchygames.events.manager import (
    AllEvents,
    AllEventStubs,
    EventManager,
)
from glitchygames.events.system_event_interfaces import (
    AppEvents,
    AppEventStubs,
    AudioEvents,
    AudioEventStubs,
    DropEvents,
    DropEventStubs,
    FontEvents,
    FontEventStubs,
    GameEvents,
    GameEventStubs,
    WindowEvents,
    WindowEventStubs,
)

__all__ = [
    'ALL_EVENTS',
    'APP_EVENTS',
    'AUDIO_EVENTS',
    'CONTROLLER_EVENTS',
    'DROP_EVENTS',
    'FPSEVENT',
    'GAMEEVENT',
    'GAME_EVENTS',
    'JOYSTICK_EVENTS',
    'KEYBOARD_EVENTS',
    'LOG',
    'MENUEVENT',
    'MIDI_EVENTS',
    'MOUSE_EVENTS',
    'TEXT_EVENTS',
    'TOUCH_EVENTS',
    'WINDOW_EVENTS',
    'AllEventStubs',
    'AllEvents',
    'AppEventStubs',
    'AppEvents',
    'AudioEventStubs',
    'AudioEvents',
    'ControllerEventStubs',
    'ControllerEvents',
    'DropEventStubs',
    'DropEvents',
    'EventInterface',
    'EventManager',
    'FontEventStubs',
    'FontEvents',
    'GameEventStubs',
    'GameEvents',
    'HashableEvent',
    'JoystickEventStubs',
    'JoystickEvents',
    'KeyboardEventStubs',
    'KeyboardEvents',
    'MidiEventStubs',
    'MidiEvents',
    'MouseEventStubs',
    'MouseEvents',
    'ResourceManager',
    'TextEventStubs',
    'TextEvents',
    'TouchEventStubs',
    'TouchEvents',
    'UnhandledEventError',
    'WindowEventStubs',
    'WindowEvents',
    'supported_events',
    'unhandled_event',
]
