[sprite]
name = "animated_sprite"

[animation]
namespace = "idle"
frame_interval = 0.5
loop = true

[animation.frame]
namespace = "idle"
frame_index = 0
pixels = """
@@@@@@@#######@@@@@@@@@@@@@@@@@@
@@@@@@@#@@@@@##@@@@@@@@@@@@@@@@@
@@@@@@@#@@@@@@##@@@@@@@@@@@@@@@@
@@@@@@@#@@@@@@@##@@@@@@@@@@@@@@@
@@@@@@@#@@@@@@@@#@@@@@@@@@@@@@@@
@@@@@@@#@@@@@@@@#@@@@@@@@@@@@@@@
@@@@@@@#@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@#@@@@@@@@@##@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@##@@@@@@@@@@@
@@@@@@@@@#@@@@@@@@@@#@@@@@@@@@@@
@@@@@@@@@@#@@@@@@@@@##@@@@@@@@@@
@@@@@@@@@@@#@@@@@@@@@#@@@@@@@@@@
@@@@@@@@@@@##@@@@@@@@#@@@@@@@@@@
@@@@@@@@@@@@@##@@@@###@@@@@@@@@@
@@@@@@@@@@@@@@@#####@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
"""

[animation.frame]
namespace = "idle"
frame_index = 1
pixels = """
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
"""

[colors]
[colors."#"]
red = 0
green = 255
blue = 0

[colors."@"]
red = 255
green = 0
blue = 0

