[sprite]
name = "Bitmap Canvas"
pixels = """
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOO.O..O.........OOOOOOO
OOOOOOOOOO.OOOOOO.OOOOOOO..OOOOO
OOOOOOOOOO.OOOOO.OOOOOOOOOO.OOOO
OOOOOOOOO.OOOOOO.OOOOOOOOOO.OOOO
OOOOOOOOO.OOOOO.OOOOOOOOOOOO.OOO
OOOOOOOOO.OOOOO.OOOOOOOOOOO..OOO
OOOOOOOOO.OOOOOOOOOOOOOOOOO.OOOO
OOOOOOOOO.OOOOOOOOOOOOOOOOO.OOOO
OOOOOOOOO.OOOOOOOOOOOOOOOO.OOOOO
OOOOOOOOOO.OOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOXXXXXOOOOOOOOO.OOOOOO
OOOOOOOOOOOXXXXOOOOOOOOO.OOOOOOO
OOOOOOOOOOXX..OOOOOOOOO.OOOOOOOO
OOOOOOOOXXXXXX.O..O....OOOOOOOOO
OOOOOOXXXOOOOOXXOOOOOOOOOOOOOOOO
OOOOOOXOOOOOOOOOXOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOXXOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOXOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOXOOOOOOOOOO
OOOOOOOOOOOOXXXXXXXXXXOOOOOOOOOO
OOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
"""

[colors]
