#!/usr/bin/env python3
"""Generate wily complexity graphs for documentation.

Produces HTML complexity graphs for the top modules ranked by cyclomatic
complexity, then writes a markdown index page that embeds them via iframes.

Usage:
    python scripts/generate_complexity_graphs.py

Output:
    docs/quality/complexity.md          -- Markdown page with embedded graphs
    docs/quality/graphs/*.html          -- Individual HTML graph files
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# How many top files to graph (by cyclomatic complexity)
TOP_N = 15

# Metrics to graph for each file
METRICS = [
    ('maintainability.mi', 'Maintainability Index'),
    ('cyclomatic.complexity', 'Cyclomatic Complexity'),
    ('raw.loc', 'Lines of Code'),
    ('halstead.effort', 'Halstead Effort'),
]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = PROJECT_ROOT / 'docs' / 'quality'
GRAPHS_DIR = DOCS_DIR / 'graphs'


def ensure_wily_cache() -> bool:
    """Check that the wily cache exists, build it if not."""
    result = subprocess.run(
        ['wily', 'index'],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )
    if result.returncode != 0:
        print('Wily cache not found. Building...')
        build_result = subprocess.run(
            ['wily', 'build'],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        if build_result.returncode != 0:
            print(f'Error building wily cache: {build_result.stderr}', file=sys.stderr)
            return False
        print('Wily cache built successfully.')
    return True


def get_top_files() -> list[str]:
    """Get the top N files ranked by cyclomatic complexity."""
    result = subprocess.run(
        ['wily', 'rank', '-n', str(TOP_N), '-m', 'cyclomatic.complexity'],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )
    if result.returncode != 0:
        print(f'Error getting file rankings: {result.stderr}', file=sys.stderr)
        return []

    files = []
    for line in result.stdout.strip().splitlines():
        # Skip header lines and empty lines
        line = line.strip()
        if not line or line.startswith('-') or line.startswith('File'):
            continue
        # First column is the file path
        parts = line.split()
        if parts and parts[0].endswith('.py'):
            files.append(parts[0])

    return files[:TOP_N]


def generate_graph(file_path: str, metric: str) -> bool:
    """Generate an HTML graph for a file and metric.

    Returns True if the graph was created successfully.
    """
    safe_name = file_path.replace('/', '_').replace('.', '_')
    metric_name = metric.replace('.', '_')
    output_path = GRAPHS_DIR / f'{safe_name}_{metric_name}.html'

    result = subprocess.run(
        ['wily', 'graph', file_path, '-m', metric, '-o', str(output_path)],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )

    if result.returncode != 0:
        # Some files may not have data for all metrics — skip silently
        return False

    return output_path.exists()


def generate_markdown_page(files: list[str], generated_graphs: dict[str, list[str]]) -> None:
    """Generate the docs/quality/complexity.md page."""
    lines = [
        '# Code Complexity Metrics',
        '',
        'Complexity trends for the top modules, generated by '
        '[wily](https://github.com/tonybaloney/wily).',
        '',
        'Regenerate with: `nox -s code-complexity -- --graphs`',
        '',
    ]

    for file_path in files:
        if file_path not in generated_graphs:
            continue

        lines.append(f'## `{file_path}`')
        lines.append('')

        for metric, metric_label in METRICS:
            safe_name = file_path.replace('/', '_').replace('.', '_')
            metric_name = metric.replace('.', '_')
            graph_file = f'{safe_name}_{metric_name}.html'
            graph_path = GRAPHS_DIR / graph_file

            if graph_path.exists():
                # Use a relative path from the markdown file to the graph
                lines.append(f'### {metric_label}')
                lines.append('')
                lines.append(
                    f'<iframe src="graphs/{graph_file}" width="100%" height="400" '
                    f'frameborder="0"></iframe>',
                )
                lines.append('')

        lines.append('---')
        lines.append('')

    md_path = DOCS_DIR / 'complexity.md'
    md_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Generated {md_path}')


def main() -> None:
    """Generate complexity graphs and documentation page."""
    if not ensure_wily_cache():
        sys.exit(1)

    GRAPHS_DIR.mkdir(parents=True, exist_ok=True)

    print(f'Getting top {TOP_N} files by cyclomatic complexity...')
    files = get_top_files()
    if not files:
        print('No files found. Is the wily cache populated?', file=sys.stderr)
        sys.exit(1)

    print(f'Found {len(files)} files. Generating graphs...')

    generated_graphs: dict[str, list[str]] = {}
    for file_path in files:
        file_graphs = []
        for metric, metric_label in METRICS:
            if generate_graph(file_path=file_path, metric=metric):
                file_graphs.append(metric)
                print(f'  {file_path}: {metric_label}')
        if file_graphs:
            generated_graphs[file_path] = file_graphs

    generate_markdown_page(files=files, generated_graphs=generated_graphs)
    print(f'\nGenerated {sum(len(v) for v in generated_graphs.values())} graphs for '
          f'{len(generated_graphs)} files.')


if __name__ == '__main__':
    main()
