#!/usr/bin/env python3
"""Generate wily complexity graphs for documentation.

Produces HTML complexity graphs for the top modules ranked by cyclomatic
complexity, then writes a markdown index page that embeds them via iframes.

Usage:
    python scripts/generate_complexity_graphs.py

Output:
    docs/quality/complexity.md          -- Markdown page with embedded graphs
    docs/quality/graphs/*.html          -- Individual HTML graph files
"""

from __future__ import annotations

import logging
import subprocess  # noqa: S404 - subprocess used to invoke trusted local dev tool (wily)
import sys
from pathlib import Path

LOG = logging.getLogger(__name__)

# How many top files to graph (by cyclomatic complexity)
TOP_N = 15

# Metrics to graph for each file
METRICS = [
    ('maintainability.mi', 'Maintainability Index'),
    ('cyclomatic.complexity', 'Cyclomatic Complexity'),
    ('raw.loc', 'Lines of Code'),
    ('halstead.effort', 'Halstead Effort'),
]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = PROJECT_ROOT / 'docs' / 'quality'
GRAPHS_DIR = DOCS_DIR / 'graphs'

WILY_CMD = 'wily'


def ensure_wily_cache() -> bool:
    """Check that the wily cache exists, build it if not.

    Returns:
        bool: True if the cache is ready, False on error.

    """
    result = subprocess.run(  # noqa: S603 - trusted local dev tool
        [WILY_CMD, 'index'],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
        check=False,
    )
    if result.returncode != 0:
        LOG.info('Wily cache not found. Building...')
        build_result = subprocess.run(  # noqa: S603 - trusted local dev tool
            [WILY_CMD, 'build'],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
            check=False,
        )
        if build_result.returncode != 0:
            LOG.error('Error building wily cache: %s', build_result.stderr)
            return False
        LOG.info('Wily cache built successfully.')
    return True


def get_top_files() -> list[str]:
    """Get the top N files ranked by cyclomatic complexity.

    Returns:
        list[str]: File paths ranked by complexity.

    """
    result = subprocess.run(  # noqa: S603 - trusted local dev tool
        [WILY_CMD, 'rank', '--limit', str(TOP_N), '--no-wrap', '--desc'],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
        check=False,
    )
    if result.returncode != 0:
        LOG.error('Error getting file rankings: %s', result.stderr)
        return []

    files: list[str] = []
    # Wily rank uses Unicode box-drawing tables with possible multiline wrapping.
    # Collect all text fragments from the first column, then join wrapped lines.
    current_path = ''
    for raw_line in result.stdout.strip().splitlines():
        line = raw_line.strip()
        # Skip header/separator/total lines
        if not line or line.startswith(('╒', '╞', '╘', '├', '-')):
            # Row boundary — flush any accumulated path
            if current_path.endswith('.py') and not current_path.startswith('tests/'):
                files.append(current_path)
            current_path = ''
            continue
        # Parse table rows: │ filepath │ value │
        if '│' in line:
            cells = [cell.strip() for cell in line.split('│') if cell.strip()]
            if not cells or cells[0] in ('File', 'Total', 'Maintainability Index'):
                continue
            # Accumulate the first column (may be wrapped across lines)
            current_path += cells[0]
    # Flush last row
    if current_path.endswith('.py') and not current_path.startswith('tests/'):
        files.append(current_path)

    return files[:TOP_N]


def generate_graph(file_path: str, metric: str) -> bool:
    """Generate an HTML graph for a file and metric.

    Returns:
        bool: True if the graph was created successfully.

    """
    safe_name = file_path.replace('/', '_').replace('.', '_')
    metric_name = metric.replace('.', '_')
    output_path = GRAPHS_DIR / f'{safe_name}_{metric_name}.html'

    result = subprocess.run(  # noqa: S603 - trusted local dev tool
        [WILY_CMD, 'graph', file_path, '-m', metric, '-o', str(output_path)],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
        check=False,
    )

    if result.returncode != 0:
        # Some files may not have data for all metrics — skip silently
        return False

    return output_path.exists()


def generate_markdown_page(files: list[str], generated_graphs: dict[str, list[str]]) -> None:
    """Generate the docs/quality/complexity.md page."""
    lines = [
        '# Code Complexity Metrics',
        '',
        (
            'Complexity trends for the top modules, generated by '
            '[wily](https://github.com/tonybaloney/wily).'
        ),
        '',
        'Regenerate with: `nox -s code-complexity -- --graphs`',
        '',
    ]

    for file_path in files:
        if file_path not in generated_graphs:
            continue

        lines.extend((f'## `{file_path}`', ''))

        for metric, metric_label in METRICS:
            safe_name = file_path.replace('/', '_').replace('.', '_')
            metric_name = metric.replace('.', '_')
            graph_file = f'{safe_name}_{metric_name}.html'
            graph_path = GRAPHS_DIR / graph_file

            if graph_path.exists():
                # Use site-root-relative path (mkdocs use_directory_urls
                # serves this page at /quality/complexity/index.html)
                lines.extend((
                    f'### {metric_label}',
                    '',
                    (
                        f'<iframe src="../graphs/{graph_file}" width="100%" height="400" '
                        f'frameborder="0"></iframe>'
                    ),
                    '',
                ))

        lines.extend(('---', ''))

    md_path = DOCS_DIR / 'complexity.md'
    md_path.write_text('\n'.join(lines), encoding='utf-8')
    LOG.info('Generated %s', md_path)


def main() -> None:
    """Generate complexity graphs and documentation page."""
    logging.basicConfig(level=logging.INFO, format='%(message)s')

    if not ensure_wily_cache():
        sys.exit(1)

    GRAPHS_DIR.mkdir(parents=True, exist_ok=True)

    LOG.info('Getting top %d files by cyclomatic complexity...', TOP_N)
    files = get_top_files()
    if not files:
        LOG.error('No files found. Is the wily cache populated?')
        sys.exit(1)

    LOG.info('Found %d files. Generating graphs...', len(files))

    generated_graphs: dict[str, list[str]] = {}
    for file_path in files:
        file_graphs: list[str] = []
        for metric, metric_label in METRICS:
            if generate_graph(file_path=file_path, metric=metric):
                file_graphs.append(metric)
                LOG.info('  %s: %s', file_path, metric_label)
        if file_graphs:
            generated_graphs[file_path] = file_graphs

    generate_markdown_page(files=files, generated_graphs=generated_graphs)
    total_graphs = sum(len(v) for v in generated_graphs.values())
    LOG.info(
        'Generated %d graphs for %d files.',
        total_graphs,
        len(generated_graphs),
    )


if __name__ == '__main__':
    main()
