[sprite]
name = "flower_tile3_32.bg"
pixels = """
FF>>>::5BBBBBMMMMBBBBB5::>>>FFFE
FFF>>::5BBBBBMMMMBBBBB5::>>FFFFE
>FFF>>:5BBBBBMMMMBBBBB5:>>FFF>>E
>>FFF>:MBB;BBBBBBBB;BBM:>FFF>>>E
>>>FFF>MBBBBBBBBBBBBBBM>FFF>>>>E
::>>F>>:MBBBBBBBBBBBBM:>>F>>:::E
:5:::>::MBBMMMMMMMMBBM::>:::555E
55555::5B;;BM5555MB;;B5::555555E
JBBBBMBB:FF5B5::5B5FF:BBMBBBBJJE
BBBBBBB;F@9:;KAAK;:9@F;BBBBBBBBE
BBB;BBB;F9?7=6<<6=7?9F;BBB;BBBBE
BBBBBBBB5:P13C44C31P:5BBBBBBBBBE
BBBBBB55B;:3GQLLQG3:;BM5BBBBBMME
MMBBBBM5506CDH88HDC6055MBBBBMMME
MMBBBBM5:ONILR22RLINO:5MBBBBMMME
MMBBBBM5:ONILR22RLINO:5MBBBBMMME
MMBBBBM5506CDH88HDC6055MBBBBMMME
BBBBBB5MB;:3GQLLQG3:;BM5BBBBBMME
BBBBBBBB5:P13C44C31P:5BBBBBBBBBE
BBB;BBB;F9?7=6<<6=7?9F;BBB;BBBBE
BBBBBBB;F@9:;KAAK;:9@F;BBBBBBBBE
JBBBBMBB:FF5B5::5B5FF:BBMBBBBJJE
55555::5B;;BM5555MB;;B5::555555E
:5:::>::MBBMMMMMMMMBBM::>:::555E
::>>F>>:MBBBBBBBBBBBBM:>>F>>:::E
>>>FFF>MBBBBBBBBBBBBBBM>FFF>>>>E
>>FFF>:MBB;BBBBBBBB;BBM:>FFF>>>E
>FFF>>:5BBBBBMMMMBBBBB5:>>FFF>>E
FFF>>:55BBBBBMMMMBBBBB55:>>FFFFE
FF>>>:55BBBBBMMMMBBBBB55:>>>FFFE
FF>>>:55BBBBBMMMMBBBBB55:>>>FFFE
F>>>::5BBBBBMMMMBBBBB5::>>>FFFEE
"""

[colors]
[colors.0]
red = 63
green = 147
blue = 87

[colors.1]
red = 23
green = 203
blue = 79

[colors.2]
red = 119
green = 27
blue = 127

[colors.3]
red = 55
green = 167
blue = 111

[colors.4]
red = 175
green = 31
blue = 191

[colors.5]
red = 63
green = 139
blue = 95

[colors.6]
red = 87
green = 119
blue = 111

[colors.7]
red = 47
green = 171
blue = 95

[colors.8]
red = 143
green = 11
blue = 159

[colors.9]
red = 47
green = 175
blue = 103

