[sprite]
name = "flower_tile2_32.bg"
pixels = """
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKAAKKKKKKKKAAKKKKKKKKKKD
KKKKKKKKA;;AKKKKKKA;;AKKKKKKKKKD
KKKKKKAA:EE5A5::5A5EE:AAKKKKKKKD
KKKKKKA;E?9:;I@@I;:9?E;AKKKKKKKD
KKKKKKA;E9>7=6<<6=7>9E;AKKKKKKKD
KKKKKKAA5:N13B44B31N:5AAKKKKKKKD
KKKKKKKKA;:3FOJJOF3:;AKKKKKKKKKD
KKKKKKKK506BCG88GCB605KKKKKKKKKD
KKKKKKKK:MLHJP22PJHLM:KKKKKKKKKD
KKKKKKKK:MLHJP22PJHLM:KKKKKKKKKD
KKKKKKKK506BCG88GCB605KKKKKKKKKD
KKKKKKKKA;:3FOJJOF3:;AKKKKKKKKKD
KKKKKKAA5:N13B44B31N:5AAKKKKKKKD
KKKKKKA;E9>7=6<<6=7>9E;AKKKKKKKD
KKKKKKA;E?9:;I@@I;:9?E;AKKKKKKKD
KKKKKKAA:EE5A5::5A5EE:AAKKKKKKKD
KKKKKKKKA;;AKKKKKKA;;AKKKKKKKKKD
KKKKKKKKKAAKKKKKKKKAAKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKD
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDD
"""

[colors]
[colors.0]
red = 63
green = 147
blue = 87

[colors.1]
red = 23
green = 203
blue = 79

[colors.2]
red = 119
green = 27
blue = 127

[colors.3]
red = 55
green = 167
blue = 111

[colors.4]
red = 175
green = 31
blue = 191

[colors.5]
red = 63
green = 139
blue = 95

[colors.6]
red = 87
green = 119
blue = 111

[colors.7]
red = 47
green = 171
blue = 95

[colors.8]
red = 143
green = 11
blue = 159

[colors.9]
red = 47
green = 175
blue = 103

