[sprite]
name = "flower_tile1_32.bg"
pixels = """
HED605MMMMMMMMMMMMMMMMMM506DEH7F
QI3:;CMMMMMMMMMMMMMMMMMMC;:3IQ@F
D31R:5CCMMMMMMMMMMMMMMCC5:R13DEF
6>8?9G;CMMMMMMMMMMMMMMC;G9?8>6NF
K;:9AG;CMMMMMMMMMMMMMMC;GA9:;KBF
5C5GG:CCMMMMMMMMMMMMMMCC:GG5C5:F
MMC;;CMMMCCMMMMMMMMCCMMMC;;CMMMF
MMMCCMMMC;;CMMMMMMC;;CMMMCCMMMMF
MMMMMMCC:GG5C5::5C5GG:CCMMMMMMMF
MMMMMMC;GA9:;KBBK;:9AG;CMMMMMMMF
MMMMMMC;G9?8>6<<6>8?9G;CMMMMMMMF
MMMMMMCC5:R13D44D31R:5CCMMMMMMMF
MMMMMMMMC;:3IQLLQI3:;CMMMMMMMMMF
MMMMMMMM506DEH77HED605MMMMMMMMMF
MMMMMMMM:POJLS22SLJOP:MMMMMMMMMF
MMMMMMMM:POJLS22SLJOP:MMMMMMMMMF
MMMMMMMM506DEH77HED605MMMMMMMMMF
MMMMMMMMC;:3IQLLQI3:;CMMMMMMMMMF
MMMMMMCC5:R13D44D31R:5CCMMMMMMMF
MMMMMMC;G9?8>6<<6>8?9G;CMMMMMMMF
MMMMMMC;GA9:;KBBK;:9AG;CMMMMMMMF
MMMMMMCC:GG5C5::5C5GG:CCMMMMMMMF
MMMCCMMMC;;CMMMMMMC;;CMMMCCMMMMF
MMC;;CMMMCCMMMMMMMMCCMMMC;;CMMMF
5C5GG:CCMMMMMMMMMMMMMMCC:GG5C5:F
K;:9AG;CMMMMMMMMMMMMMMC;GA9:;KBF
6>8?9G;CMMMMMMMMMMMMMMC;G9?8>6NF
D31R:5CCMMMMMMMMMMMMMMCC5:R13DEF
QI3:;CMMMMMMMMMMMMMMMMMMC;:3IQ@F
HED605MMMMMMMMMMMMMMMMMM506DEH7F
7@ENB:MMMMMMMMMMMMMMMMMM:BNE@7=F
@ENB:MMMMMMMMMMMMMMMMMM:BNE@7=FF
"""

[colors]
[colors.0]
red = 63
green = 147
blue = 87

[colors.1]
red = 23
green = 203
blue = 79

[colors.2]
red = 119
green = 27
blue = 127

[colors.3]
red = 55
green = 167
blue = 111

[colors.4]
red = 175
green = 31
blue = 191

[colors.5]
red = 63
green = 139
blue = 95

[colors.6]
red = 87
green = 119
blue = 111

[colors.7]
red = 143
green = 11
blue = 159

[colors.8]
red = 47
green = 171
blue = 95

[colors.9]
red = 47
green = 175
blue = 103

