[sprite]
name = "flower_tile1_32.bg"
pixels = """
HED605MMMMMMMMMMMMMMMMMM506DEH7F
QI3:;CMMMMMMMMMMMMMMMMMMC;:3IQ@F
D31R:5CCMMMMMMMMMMMMMMCC5:R13DEF
6>8?9G;CMMMMMMMMMMMMMMC;G9?8>6NF
K;:9AG;CMMMMMMMMMMMMMMC;GA9:;KBF
5C5GG:CCMMMMMMMMMMMMMMCC:GG5C5:F
MMC;;CMMMCCMMMMMMMMCCMMMC;;CMMMF
MMMCCMMMC;;CMMMMMMC;;CMMMCCMMMMF
MMMMMMCC:GG5C5::5C5GG:CCMMMMMMMF
MMMMMMC;GA9:;KBBK;:9AG;CMMMMMMMF
MMMMMMC;G9?8>6<<6>8?9G;CMMMMMMMF
MMMMMMCC5:R13D44D31R:5CCMMMMMMMF
MMMMMMMMC;:3IQLLQI3:;CMMMMMMMMMF
MMMMMMMM506DEH77HED605MMMMMMMMMF
MMMMMMMM:POJLS22SLJOP:MMMMMMMMMF
MMMMMMMM:POJLS22SLJOP:MMMMMMMMMF
MMMMMMMM506DEH77HED605MMMMMMMMMF
MMMMMMMMC;:3IQLLQI3:;CMMMMMMMMMF
MMMMMMCC5:R13D44D31R:5CCMMMMMMMF
MMMMMMC;G9?8>6<<6>8?9G;CMMMMMMMF
MMMMMMC;GA9:;KBBK;:9AG;CMMMMMMMF
MMMMMMCC:GG5C5::5C5GG:CCMMMMMMMF
MMMCCMMMC;;CMMMMMMC;;CMMMCCMMMMF
MMC;;CMMMCCMMMMMMMMCCMMMC;;CMMMF
5C5GG:CCMMMMMMMMMMMMMMCC:GG5C5:F
K;:9AG;CMMMMMMMMMMMMMMC;GA9:;KBF
6>8?9G;CMMMMMMMMMMMMMMC;G9?8>6NF
D31R:5CCMMMMMMMMMMMMMMCC5:R13DEF
QI3:;CMMMMMMMMMMMMMMMMMMC;:3IQ@F
HED605MMMMMMMMMMMMMMMMMM506DEH7F
7@ENB:MMMMMMMMMMMMMMMMMM:BNE@7=F
@ENB:MMMMMMMMMMMMMMMMMM:BNE@7=FF
"""

[colors]
# Flower tile colors - bright and vibrant
"H" = { red = 255, green = 200, blue = 100 }  # Golden yellow
"E" = { red = 255, green = 100, blue = 50 }    # Orange
"D" = { red = 200, green = 50, blue = 100 }   # Pink
"6" = { red = 150, green = 100, blue = 200 }  # Purple
"0" = { red = 100, green = 150, blue = 255 }  # Light blue
"5" = { red = 50, green = 200, blue = 100 }   # Green
"M" = { red = 100, green = 100, blue = 100 }  # Gray
"Q" = { red = 255, green = 255, blue = 200 }  # Light yellow
"I" = { red = 200, green = 200, blue = 255 }  # Light purple
"3" = { red = 150, green = 255, blue = 150 } # Light green
":" = { red = 255, green = 150, blue = 150 }  # Light pink
";" = { red = 150, green = 150, blue = 255 }  # Light blue
"C" = { red = 200, green = 200, blue = 200 }  # Light gray
"G" = { red = 100, green = 255, blue = 100 }  # Bright green
"9" = { red = 255, green = 200, blue = 100 }  # Golden
"?" = { red = 200, green = 100, blue = 255 }  # Magenta
"8" = { red = 100, green = 200, blue = 255 }  # Sky blue
">" = { red = 255, green = 100, blue = 200 }  # Hot pink
"R" = { red = 255, green = 150, blue = 50 }   # Orange-red
"1" = { red = 255, green = 255, blue = 100 }  # Yellow
"F" = { red = 255, green = 255, blue = 255 }  # White
"K" = { red = 50, green = 50, blue = 50 }     # Dark gray
"B" = { red = 0, green = 0, blue = 255 }      # Blue
"N" = { red = 255, green = 100, blue = 100 }  # Light red
"@" = { red = 255, green = 200, blue = 50 }   # Gold
"P" = { red = 200, green = 100, blue = 200 }  # Pink
"O" = { red = 255, green = 150, blue = 100 }  # Peach
"J" = { red = 100, green = 255, blue = 200 }  # Mint
"L" = { red = 200, green = 255, blue = 100 }  # Lime
"S" = { red = 100, green = 200, blue = 255 }  # Light blue
"2" = { red = 255, green = 255, blue = 200 }  # Cream
"7" = { red = 200, green = 200, blue = 100 }  # Olive
"4" = { red = 255, green = 200, blue = 150 }  # Light orange
"A" = { red = 100, green = 255, blue = 100 }  # Bright green
"<" = { red = 200, green = 200, blue = 100 }  # Light yellow
"=" = { red = 255, green = 100, blue = 100 }  # Light red