[sprite]
name = "Mario Jump"
description = """A n animated soprite from your favorite video game
"""

[[animation]]
namespace = "jump"
frame_interval = 0.5
loop = true

[[animation.frame]]
namespace = "jump"
frame_index = 0
pixels = """
.....RRRRR.....
....RRRRRRR....
....BBBWBW.....
...BWBWWWBW....
...BWBWWWBBW...
...BBWWWWBBB...
.....WWWWW.....
....RRBRRR.....
...RRRBRRRR....
..RRRRBRRRRRR..
..WWRRBRRRBWW..
..WWWBBBBWWW...
..WWBBBBBBBW...
....BBBB.BBB...
...BBBBB.BBBB..
..BBBBBB.BBBBB.
"""

[[animation.frame]]
namespace = "jump"
frame_index = 1
pixels = """
.....RRRRR.....
....RRRRRRR....
....BBBWBW.....
...BWBWWWBW....
...BWBWWWBBW...
...BBWWWWBBB...
.....WWWWW.....
...RRRBRRR.....
..RRRRBRRRRR...
.RRRRRBRRRRRR..
WWWRRBRRRBWWW..
.WWWBBBBBBWW...
..WBBBBBBBW....
...BBBBBBB.....
..BBBB..BBBB...
.BBBBB..BBBBB..
"""

[[animation.frame]]
namespace = "jump"
frame_index = 2
pixels = """
.....RRRRR.....
....RRRRRRR....
....BBBWBW.....
...BWBWWWBW....
...BWBWWWBBW...
...BBWWWWBBB...
.....WWWWW.....
....RRRRRR.....
.RRRRBRRRRR....
RRRRRBRRRRRR...
WWRRBRRRBWW....
WWWBBBBBBWW....
WWBBBBBBBBW....
...BBBBBBBB....
....BBB..BBB...
...BBBB..BBBB..
"""

[[animation.frame]]
namespace = "jump"
frame_index = 3
pixels = """
.....RRRRR.....
....RRRRRRR....
....BBBWBW.....
...BWBWWWBW....
...BWBWWWBBW...
...BBWWWWBBB...
.....WWWWW.....
....RRRRRR.....
...RRBRRRRR....
..RRRBRRRRRR...
..WRRBRRRBW....
..WWBBBBBBWW...
...WBBBBBBBBW..
....BBBBBBBBB..
....BBB...BBB..
...BBBB...BBBB.
"""

[colors]
[colors."."]
red = 255
green = 0
blue = 255

[colors."R"]
red = 255
green = 0
blue = 0

[colors."B"]
red = 139
green = 69
blue = 19

[colors."W"]
red = 255
green = 215
blue = 0

