[sprite]
name = "jumping_slime_with_tiara"
description = """Make me a slime wearing a tiara with googley eyes that is
jumping
in
place
up and down, and its body blubber ripples dramatically after it
lands before it finally returns to his normal shape over 20 frames
animating over 3.00 seconds and you can make different frames be
different frame_intervals if you want to, for instance, have the top of
its jump seem like he's stopped in mid air for a split second, as long
as the total animation time is 3.00 seconds total.  Make the landing
be dramatic.  16x16 pixels """

[[animation]]
namespace = "jump"
frame_interval = 0.1
loop = true

[[animation.frame]]
namespace = "jump"
frame_index = 0
pixels = """
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....bbbbbbBB....
...bBBBBBBbBB...
..bBBcBBcBBbB...
..bBcCCcCCBbB...
..bBcCCcCCBbB...
..bBBBBBBBBbB...
...bBBBBBBbBB...
....bbbbbbBB....
"""

[[animation.frame]]
namespace = "jump"
frame_index = 1
pixels = """
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
"""

[[animation.frame]]
namespace = "jump"
frame_index = 2
pixels = """
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 3
pixels = """
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 4
pixels = """
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
................
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 5
pixels = """
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
................
................
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 6
frame_interval = 0.25
pixels = """
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
................
................
................
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 7
pixels = """
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
................
................
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 8
pixels = """
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....DDDDDD.....
................
................
"""

[[animation.frame]]
namespace = "jump"
frame_index = 9
pixels = """
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDdDDD...
....ddddddDD....
"""

[[animation.frame]]
namespace = "jump"
frame_index = 10
pixels = """
................
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....dddddddDD...
..ddDDDDDDDDdDD.
.dDDDcDDcDDDdDD.
.dDDcCCcCCDDdDD.
.dDDcCCcCCDDdDD.
.dDDDDDDDDDDdDD.
..ddDDDDDDddDD..
"""

[[animation.frame]]
namespace = "jump"
frame_index = 11
pixels = """
................
................
................
................
................
................
................
................
......aAaa......
....aAAAAa......
...ddddddddDD...
.ddDDDDDDDDDdDD.
dDDDDcDDcDDDDdDD
dDDDcCCcCCDDDdDD
dDDDcCCcCCDDDdDD
dDDDDDDDDDDDDdDD
"""

[[animation.frame]]
namespace = "jump"
frame_index = 12
pixels = """
................
................
................
................
................
................
................
................
................
......aAaa......
...aaAAAAAaDD...
.ddDDDDDDDDDDdD.
dDDDDceecDDDDdDD
dDDDcCCcCCDDDdDD
dDDDcCCcCCDDDdDD
dDDDDDDDDDDDDdDD
"""

[[animation.frame]]
namespace = "jump"
frame_index = 13
pixels = """
................
................
................
................
................
................
................
................
................
......aAaa......
...aaAAAAAaDD...
.ddDDDDDDDDDdDD.
dDDDDceecDDDdDDD
dDDDcCCcCCDDdDDD
dDDDcCCcCCDDdDDD
dDDDDDDDDDDDdDDD
"""

[[animation.frame]]
namespace = "jump"
frame_index = 14
pixels = """
................
................
................
................
................
................
................
................
......aAaa......
....aAAAAa......
...ddddddddDD...
.ddDDDDDDDDDdDD.
dDDDDcDDcDDDDdDD
dDDDcCCcCCDDDdDD
dDDDcCCcCCDDDdDD
dDDDDDDDDDDDDdDD
"""

[[animation.frame]]
namespace = "jump"
frame_index = 15
pixels = """
................
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....dddddddDD...
..ddDDDDDDDDdDD.
.dDDDcDDcDDDdDD.
.dDDcCCcCCDDdDD.
.dDDcCCcCCDDdDD.
.dDDDDDDDDDDdDD.
..ddDDDDDDddDD..
"""

[[animation.frame]]
namespace = "jump"
frame_index = 16
pixels = """
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDdDDD...
....ddddddDD....
"""

[[animation.frame]]
namespace = "jump"
frame_index = 17
pixels = """
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
.....eDDDDe.....
"""

[[animation.frame]]
namespace = "jump"
frame_index = 18
pixels = """
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
"""

[[animation.frame]]
namespace = "jump"
frame_index = 19
pixels = """
................
................
................
................
................
................
......aAaa......
.....aAAAAa.....
....ddddddDD....
...dDDDDDDdDD...
..dDDcDDcDDdD...
..dDcCCcCCDdD...
..dDcCCcCCDdD...
..dDDDDDDDDdD...
...dDDDDDDdDD...
....ddddddDD....
"""

[colors]
[colors."."]
red = 255
green = 0
blue = 255

[colors."a"]
red = 255
green = 215
blue = 0

[colors."A"]
red = 220
green = 180
blue = 0

[colors."b"]
red = 80
green = 220
blue = 120
alpha = 137

[colors."B"]
red = 60
green = 180
blue = 90
alpha = 137

[colors."c"]
red = 0
green = 0
blue = 0

[colors."C"]
red = 255
green = 255
blue = 255

[colors."d"]
red = 80
green = 220
blue = 120
alpha = 137

[colors."D"]
red = 60
green = 180
blue = 90
alpha = 137

[colors."e"]
red = 40
green = 140
blue = 70

