[sprite]
name = "idle"
pixels = """
..........aa.........aaa........
..........a............aa.......
........aa..............a.......
........a................a......
........a.......................
.......a.....a............a.....
.......a....a...................
......a....a..............a.....
......a....a....................
...........a..............a.....
......a...aa..............a.....
.....a....a.....................
.....a....a..............a......
.....a....a..............a......
.....aa...a.....................
......aa..a...........aa........
........aaa...........aa........
..........aa.........aa.........
...........a.aa.a.a.a...........
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
"""

[colors]
"." = { red = 255, green = 0, blue = 255 }
"a" = { red = 0, green = 0, blue = 0 }
