[sprite]
name = "animated_sprite"
pixels = """
................
................
.....aaaaaa.....
...aaaaaaaaaa...
..aaaAaaAaAaaa..
.aaaaaaaaaaaaaa.
.aaaAaaaAaaAaaa.
.aaaaaaaaaaaaaa.
..aaaaaaaaaaaa..
................
....AAAAAAAA....
....AAAAAAAA....
...AAAAAAAAAA...
...AAAAAAAAAA...
...AAAAAAAAAA...
....AAAAAAAA....
.....AAAAAA.....
................
"""

[colors]
"█" = { red = 255, green = 0, blue = 255, alpha = 255 }
"." = { red = 0, green = 0, blue = 0 }
"a" = { red = 255, green = 0, blue = 0 }
"A" = { red = 255, green = 255, blue = 255 }
